### ISSUE TITLE
Sign into google

### ISSUE THREAD

**Issue by kathlu** [pizza442/BeatTheLag#1]
Minor issue: I clicked the sign in with google button. It asks me to allow permissions to access my google calendar. I chose to allow access to my google calendar. Once I am signed in, I am taken back to the home screen with the button "Sign In With Google." I clicked on the "Sign in with google" button again and was prompted to log in again. After I repeated the sign in process, I was taken back to the same screen with "the button "Sign In With Google." A few seconds later, I am taken to the screen to input my options and use the application.

This is confusing as I was prompted with a sign in button after I already signed into my google account. It seems like after I sign in, I have to wait a few seconds before I am directed to the application. Especially after the user has signed in already, it is confusing to have the sign in button appear at all.

Reproduction Steps:
1. Click 'sign in with Google' button
2. Sign into google and allow permissions
3. After log in, user redirected to same page as before 'sign in with Google button'
4. Click 'sign in with Google' button again

![Untitled](https://user-images.githubusercontent.com/26660940/59239722-5dc55400-8bb7-11e9-992d-9ab5a7301b9a.gif)

**Comment by s21dy** [comment]
We have add the loading feature while the page is changing.

**Comment by sKhan16** [comment]
Fixed in commit 81ff8d3a609480c4762e25f7c4ad8218c5e435d0
