### ISSUE TITLE
Fail to modify generated schedules

### ISSUE THREAD

**Issue by rheaxychen** [pizza442/BeatTheLag#10]
![Screen Shot 2019-06-10 at 7 44 11 PM](https://user-images.githubusercontent.com/24926110/59239981-315e0780-8bb8-11e9-9282-cf4afa8a3b27.png)

Besides not showing up in the Google Calendar, the webapp does not support schedule modification. Users cannot go back and revisit the generated lag schedules and make changes either on the website let alone in their personal calendar.

**Comment by aliar97** [comment]
Our team met an issues with Google calendar api that it' not allowing us to adjust users schedule since we are not a verified app. It takes over 3 weeks to get the verification so it is not feasible for us to accomplish this feature. Our requirements have been adjusted accordingly.
