### ISSUE TITLE
Time Zone Meaning

### ISSUE THREAD

**Issue by yiranni** [pizza442/BeatTheLag#11]
There are multiple time zones provided, but users may not know what each time zone stands for. For example, I am heading to China, but which time zone should I choose? Maybe have a different way to choose time?

**Comment by s21dy** [comment]
Thank you for this advise! 
Our team did try to using a city and country to capture the time zone in the first place. Yet, the only API we found cost money and that's a violation to the purpose of the course. That's why we decide to use UTC time zone rather than actual location for the option.
