### ISSUE TITLE
Your bed time and wake up time cannot be the same

### ISSUE THREAD

**Issue by clairehjk** [pizza442/BeatTheLag#13]
I am getting a "Your bed time and wake up time cannot be the same" error.
See configuration below:

<img width="200" alt="Screen Shot 2019-06-11 at 12 23 18 AM" src="https://user-images.githubusercontent.com/20443687/59251697-4bf7a700-8bdf-11e9-953e-9066d05e9bcb.png">

Also I'm not sure if you should enable users to put in dates further back.

**Comment by aliar97** [comment]
fixed this issue thanks for pointing it out!

**Comment by aliar97** [comment]
fixed with 916986bb594d85ad9de2dd5a8c07beedddd58098
