### ISSUE TITLE
Sign in with Google bug after signing in

### ISSUE THREAD

**Issue by bbalansay** [pizza442/BeatTheLag#15]
After signing in, the sign in with Google button still appears on the screen for a period of time. This has led me to believe that I have not signed myself in, clicking upon the button only to realize that if I waited I would have been shown the controls.

**Comment by s21dy** [comment]
Thank you for the report!
We have add the loading feature so the sign in screen won't show up after you click sign in.

**Comment by sKhan16** [comment]
Fixed in build 81ff8d3a609480c4762e25f7c4ad8218c5e435d0
