### ISSUE TITLE
Start and end dates are not checked for errors

### ISSUE THREAD

**Issue by bbalansay** [pizza442/BeatTheLag#16]
The start date of the trip can be in the year 2010, while the end date for that same trip can be in the year 1990. No logic exists to check whether the dates are valid. If the dates have already passed, it should be invalid. Same goes for if the end is before the start.

**Comment by aliar97** [comment]
we have patched this now thanks for sharing!

**Comment by aliar97** [comment]
fixed with 916986bb594d85ad9de2dd5a8c07beedddd58098
