### ISSUE TITLE
Minor: Sign in button after signing in

### ISSUE THREAD

**Issue by rioishii** [pizza442/BeatTheLag#17]
This is a minor user experience issue but when a user signs, they are led to the same user sign in page with the sign in button for a couple seconds. 

Reproduction steps:
1. Sign in
2. The sign in button appears again but then disappears after few seconds

**Comment by aliar97** [comment]
fixed this with a loading screen thanks sharing

**Comment by sKhan16** [comment]
Fixed in build 81ff8d3a609480c4762e25f7c4ad8218c5e435d0
