### ISSUE TITLE
generate schedules that are before the flight

### ISSUE THREAD

**Issue by jinc132** [pizza442/BeatTheLag#18]
After I sign in and I choose a schedule from 6/10 to 6/1,  it generates schedules that are before the flight schedule. Which is not particularly useful. Moreover, instead of showing the values plotting the values into a visual such as a calendar maybe more helpful.

**Comment by aliar97** [comment]
fixed this issue as well thanks for notifying

**Comment by aliar97** [comment]
916986bb594d85ad9de2dd5a8c07beedddd58098 fixed this issue
