### ISSUE TITLE
Allows use to make trips with a start date later than the end date

### ISSUE THREAD

**Issue by JessicaXLou** [pizza442/BeatTheLag#19]
![image](https://user-images.githubusercontent.com/32353106/59307630-c19d5a80-8c53-11e9-89fa-b3215921dde8.png)
There is no verification that the start date is before the end date. When I put in a start date that is later, the app continues to work as it usually would and creates a schedule.

**Comment by JessicaXLou** [comment]
![image](https://user-images.githubusercontent.com/32353106/59307706-f8737080-8c53-11e9-8233-5fa972214e11.png)

**Comment by aliar97** [comment]
already fixed this issue

**Comment by aliar97** [comment]
fixed with 916986bb594d85ad9de2dd5a8c07beedddd58098
