### ISSUE TITLE
Allows user to add trips where the start date is way after the end date

### ISSUE THREAD

**Issue by emilytao19** [pizza442/BeatTheLag#3]
<img width="829" alt="Screen Shot 2019-06-10 at 4 13 21 PM" src="https://user-images.githubusercontent.com/32439428/59232791-b3d7ce80-8b9a-11e9-9975-66025a69c529.png">

**Comment by emilytao19** [comment]
Create a new plan with all the fields listed above; the end date above is 4 months before the start date, and see that it still says your schedule has been generated.

**Comment by aliar97** [comment]
we have addressed this issue thank you for bringing it up

**Comment by aliar97** [comment]
fixed with 916986bb594d85ad9de2dd5a8c07beedddd58098
