### ISSUE TITLE
What is the point of a sign in

### ISSUE THREAD

**Issue by dayoungcheong** [pizza442/BeatTheLag#4]
I guess this is more of a design problem than an actual bug but there seems to be literally no reason to have a sign in page. You cannot save your past results and when you relogin (since the only option is to sign out after getting your results), there is no way to get to your past results. This seems to be a major issue with your app.

**Comment by aliar97** [comment]
We were originally gonna use the google calender api but to do that we needed to go through a verification process that takes weeks to complete so it wasn't feasible for us to do that. Our requirements have been adjusted accordingly
