### ISSUE TITLE
Edge Case flight

### ISSUE THREAD

**Issue by lbc546** [pizza442/BeatTheLag#7]
Hey, 
As I mentioned in class, for flights departing from Russia to Alaska, the thing would not work. It will be very inaccurate, if the actually time difference is -12 - 12 which is basically 0 hour but the lag time reminder tells me to change sleeping schedule 24 days in advance and get all the way around from counter-clockwise. There should be something that handles the edge case like this. This could be minor since there is no commercial flight between Poluostrov Kamchatka and Alasaka, but this is the case to consider

**Comment by s21dy** [comment]
Since UTC 12 is basically UTC -12, we have fix this edge case by taking away "UTC 12" in the dropdown. Our dropdown does not suppose to have a repeated timezone. 
See line 11 in input.js

**Comment by s21dy** [comment]
fix with commit 83bd6507013cf9890908dadb0092026c7e76a212
