### ISSUE TITLE
Direct the user to add schedule into GoogleCalendar

### ISSUE THREAD

**Issue by rheaxychen** [pizza442/BeatTheLag#8]
![Screen Shot 2019-06-10 at 7 34 51 PM](https://user-images.githubusercontent.com/24926110/59239615-f8716300-8bb6-11e9-892d-c658c0f7d984.png)

Nothing happens now after successfully created a lag schedule.
Steps: 

1. Having a button that allows users to add the lag schedule into their GoogleCalendar
2. Stretch goal: allow users to download an .ics file which can be imported into any calendar app.
3. Stretch goal: allow users to modify the lag schedule according to their actual schedule inside their calendar and updated to the website accordingly.

**Comment by sKhan16** [comment]
Thanks for the feedback! We were not able to bring the feature to add to a user's Google calendar in this build of our site that getting the verification will cost over 3 weeks, but we will still be working hard to implement it in further builds (as long as Google decides to play nice)! However, this is not a bug we still appreciate the advice, thanks again!
